name: coach_app
description: Kişisel Antrenor Uygulamasi

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  
  # UI & Utils
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  video_player: ^2.8.2
  chewie: ^1.7.4
  fl_chart: ^1.1.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  uuid: ^4.3.3
  
  # YouTube Player - YENİ
  youtube_player_iframe: ^5.2.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  haptic_feedback: ^0.6.4+3
  connectivity_plus: ^7.0.0
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.2
  syncfusion_flutter_charts: ^32.2.7
  local_auth: ^3.0.0
  shared_preferences: ^2.5.4
  flutter_tilt: ^3.3.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  open_file: ^3.5.11
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash_logo.png"
  background_image: "assets/images/bg_main.png"
  android_12:
    color: "#000000"
    image: "assets/images/splash_logo.png"
    icon_background_color: "#000000"
  fullscreen: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_main.png
    - assets/images/app_logo.png
    - assets/images/splash_logo.png